<?php

namespace Verge\OpenAPIGenerator\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class SchemaDefinition extends Model
{
    /**
     * Get the table name with prefix.
     */
    public function getTable(): string
    {
        $prefix = config('openapi-generator.table_prefix', 'openapi_');
        return $prefix . 'schemas';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array<string>
     */
    protected $fillable = [
        'name',
        'source_class',
        'schema_type',
        'schema',
        'title',
        'description',
        'example',
        'refs',
        'is_auto_generated',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'schema' => 'array',
        'example' => 'array',
        'refs' => 'array',
        'is_auto_generated' => 'boolean',
    ];

    /**
     * Scope a query to only include auto-generated schemas.
     */
    public function scopeAutoGenerated(Builder $query): Builder
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope a query to only include manually defined schemas.
     */
    public function scopeManual(Builder $query): Builder
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Scope a query to filter by source class.
     */
    public function scopeFromClass(Builder $query, string $class): Builder
    {
        return $query->where('source_class', $class);
    }

    /**
     * Find a schema by its source class.
     */
    public static function findByClass(string $class): ?self
    {
        return static::where('source_class', $class)->first();
    }

    /**
     * Create or update a schema from a source class.
     */
    public static function updateOrCreateFromClass(string $class, array $schema, string $name = null): self
    {
        $schemaName = $name ?? class_basename($class);

        return static::updateOrCreate(
            ['source_class' => $class],
            [
                'name' => $schemaName,
                'schema_type' => $schema['type'] ?? 'object',
                'schema' => $schema,
                'is_auto_generated' => true,
            ]
        );
    }

    /**
     * Get the OpenAPI schema definition.
     */
    public function toOpenAPISchema(): array
    {
        $schema = $this->schema;

        if ($this->title) {
            $schema['title'] = $this->title;
        }

        if ($this->description) {
            $schema['description'] = $this->description;
        }

        if ($this->example) {
            $schema['example'] = $this->example;
        }

        return $schema;
    }

    /**
     * Get the $ref string for this schema.
     */
    public function getRefString(): string
    {
        return '#/components/schemas/' . $this->name;
    }

    /**
     * Get all schemas that this schema references.
     */
    public function getReferencedSchemas(): array
    {
        if (!$this->refs) {
            return [];
        }

        return static::whereIn('name', $this->refs)->get()->all();
    }
}
